### ISSUE TITLE
props do not work in Tabs.Item

### ISSUE THREAD

**Issue by GuichiZhao** [zeit-ui/react#333] opened 2020-07-14 09:23 UTC
# Bug report 🐞

## Version & Environment

  - Version of browser
  - Version of `zeit-ui/react`

## Expection

<img width="588" alt="截屏2020-07-14 下午5 21 21" src="https://user-images.githubusercontent.com/12082547/87408711-742db280-c5f6-11ea-84a1-febc4817c9f8.png">

## Actual results (or Errors)
The UI is not sync with `props`. i.e. when the `label` props changed, the UI still renders the initial `label`
I got an error:

```
code
```
<img width="758" alt="截屏2020-07-14 下午5 22 57" src="https://user-images.githubusercontent.com/12082547/87408854-ab03c880-c5f6-11ea-8998-5d37e621044d.png">

you tried to sync the data through `register`, However, this only happens once when the component receives the initial props and all the upcoming props will not trigger the `register` function

**Comment by unix** [comment] 2020-07-14 10:22
Good point. This is to automatically generate a unique key when `value` is missing, now it seems that using `label` as a key will cause `label` to stop updating, I created a pull-request to fix it.

But the feature to update the `label` results in a small range of breaking changes: we must require that `value` is required. So I will only release it in the `canary` version. It will not be merged into the stable version until `v1.8.0` is officially released.

For #334 , is there anything else you need to add?

**Comment by GuichiZhao** [comment] 2020-07-15 02:07
Not sure what are you talking about, I suppose the cause of the bug is `register` is not triggered properly rather than the way how the key is assigned. `disable` property is subject to the same issue. I suppose the fix is to add dependencies to `useEffect` in `tab-items.js`  in order to trigger `register` when necessary

**Comment by unix** [comment] 2020-07-15 05:53
Thank you for your update and discussion again.
I know what you mean, but the issue to be considered here is not a simple `effect`, imagine a scene like this:
  1. In the [origin design](https://github.com/zeit-ui/react/blob/9c0720bc87f519118b2220aa154914bac2cb3af5/components/tabs/tabs-item.tsx#L23), `value` is not required. when the `value` does not exist, `label` is used as the `key`.
  2. If you track the change of `label`, the uniqueness of the changed tab cannot be determined.
  3, When the `label` changes, the component will add a tab, because [the unique key is added](https://github.com/zeit-ui/react/blob/9c0720bc87f519118b2220aa154914bac2cb3af5/components/tabs/tabs.tsx#L38).

This is why the `label` was not tracked in the original design, If we simply track changes, we may have the following issues:

  - Every time `label` changes, a new tab is added.
  - The array of tabs always be added list, and it will always be in the last bit after the tabs is changed. Because the removal of subcomponent(`Tabs.Item`) will also log off the registered tab.

I quite understand what you think, but the root of the issue is not `useEffect`, you can try to add a change dependency, and you won't get the result you want when `value` is missing. It's a matter of context and design, the original design provides the default function of using `label` instead of `value`, now in order to track `label`, I have to remove it.

Looking forward to your opinions, but I don't know you've ever tried to change them or just run in local, or you can try reading #334 , breaking change is still necessary, isn't it? Anyway, it looks like you've learned `useEffect`, it's a good thing, and I'm happy for you. Have a good day.

**Comment by GuichiZhao** [comment] 2020-07-15 06:28
> 2. If you track the change of label, the uniqueness of the changed tab cannot be determined.
> 3 When the label changes, the component will add a tab, because the unique key is added.

Not 100% sure what are you talking about, the reason I need to update label is a translation issue, and keep tracking of label props just work for us. Not sure why the uniqueness is necessary. It looks OK for me. There is no visible bug, maybe your consideration is performance.

**Comment by unix** [comment] 2020-07-15 06:34
> At the mean time, the old tab will also be removed，remember that the "clearup" function is returned from useEffect.

If there are many tabs, we must make sure that they are rendered in the same order, otherwise, the tab will be added at the end each time.

**Comment by GuichiZhao** [comment] 2020-07-15 06:45
You are right, the order is messed up when label changed, I just tried

**Comment by unix** [comment] 2020-07-15 10:29
Version `v1.8.0-canary.6` is now available. 
  - [release note](https://github.com/zeit-ui/react/releases/tag/v1.8.0-canary.6)
  - [npm](https://www.npmjs.com/package/@zeit-ui/react/v/1.8.0-canary.6)

**Closed by unix** 2020-07-15 10:29 UTC
Labels: bug
